//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FoldersRequestLog
    {
        public int fld_FoldersRequstLogID { get; set; }
        public Nullable<int> fld_FK_FoldersID { get; set; }
        public Nullable<int> fld_FK_FoldersRequestStatusID { get; set; }
        public string fld_FolderRequestLog_PersonModified { get; set; }
        public Nullable<int> fld_FolderRequestLogHDate { get; set; }
        public Nullable<System.DateTime> fld_FolderRequestLogMDate { get; set; }
        public Nullable<int> fld_FolderRequestLogPreviousFolderID { get; set; }
        public Nullable<bool> fld_ShowLastLog { get; set; }
    
        public virtual Tbl_Folders Tbl_Folders { get; set; }
        public virtual Tbl_FoldersRequstStatus Tbl_FoldersRequstStatus { get; set; }
    }
}
