//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Folders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Folders()
        {
            this.Tbl_FoldersRequestLog = new HashSet<Tbl_FoldersRequestLog>();
            this.Tbl_Access = new HashSet<Tbl_Access>();
        }
    
        public int fld_FolderID { get; set; }
        public int fld_FK_FolderOwner { get; set; }
        public string fld_FolderAddress { get; set; }
        public Nullable<int> fld_SuggestedSpace { get; set; }
        public Nullable<int> fld_ApprovedSpace { get; set; }
        public Nullable<bool> fld_FolderShow { get; set; }
        public string fld_SuggestedAddress { get; set; }
        public string fld_SuggestedName { get; set; }
        public Nullable<bool> fld_AdminCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FoldersRequestLog> Tbl_FoldersRequestLog { get; set; }
        public virtual Tbl_FoldersOwner Tbl_FoldersOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Access> Tbl_Access { get; set; }
    }
}
