//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FoldersRequstStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FoldersRequstStatus()
        {
            this.Tbl_FoldersRequestLog = new HashSet<Tbl_FoldersRequestLog>();
        }
    
        public int fld_FoldersRequestStatusID { get; set; }
        public Nullable<int> fld_FoldersRequestStatusCode { get; set; }
        public string fld_FoldersRequestStatusDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FoldersRequestLog> Tbl_FoldersRequestLog { get; set; }
    }
}
