//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_FSRMEntities : DbContext
    {
        public db_FSRMEntities()
            : base("name=db_FSRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_AccessEmailsLog> Tbl_AccessEmailsLog { get; set; }
        public virtual DbSet<Tbl_AccessStatus> Tbl_AccessStatus { get; set; }
        public virtual DbSet<Tbl_Department> Tbl_Department { get; set; }
        public virtual DbSet<Tbl_Folders> Tbl_Folders { get; set; }
        public virtual DbSet<Tbl_FoldersEmailsLog> Tbl_FoldersEmailsLog { get; set; }
        public virtual DbSet<Tbl_FoldersOwner> Tbl_FoldersOwner { get; set; }
        public virtual DbSet<Tbl_FoldersRequestLog> Tbl_FoldersRequestLog { get; set; }
        public virtual DbSet<Tbl_FoldersRequstStatus> Tbl_FoldersRequstStatus { get; set; }
        public virtual DbSet<Tbl_Personnel> Tbl_Personnel { get; set; }
        public virtual DbSet<Tbl_AccessLog> Tbl_AccessLog { get; set; }
        public virtual DbSet<Tbl_Access> Tbl_Access { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Admins> Tbl_Admins { get; set; }
    }
}
