//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AccessStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_AccessStatus()
        {
            this.Tbl_AccessLog = new HashSet<Tbl_AccessLog>();
        }
    
        public int fld_AccessStatusID { get; set; }
        public int fld_AccessStatusCode { get; set; }
        public string fld_AccessStatusDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AccessLog> Tbl_AccessLog { get; set; }
    }
}
