//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FoldersOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FoldersOwner()
        {
            this.Tbl_Folders = new HashSet<Tbl_Folders>();
        }
    
        public int fld_FolderOwnerID { get; set; }
        public Nullable<int> fld_FK_FolderOwnerOU { get; set; }
        public string fld_FolderOwnerName { get; set; }
        public string fld_FolderOwnerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Folders> Tbl_Folders { get; set; }
    }
}
