//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admins
    {
        public int fld_AdminID { get; set; }
        public string fld_AdminName { get; set; }
        public string fld_AdminADName { get; set; }
        public Nullable<bool> fld_AdminShow { get; set; }
        public Nullable<int> fld_AdminStatus { get; set; }
        public Nullable<System.DateTime> fld_AdminMDateA { get; set; }
        public Nullable<System.DateTime> fld_AdminMDateR { get; set; }
    }
}
