//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSRM.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AccessLog
    {
        public int fld_AccessLogID { get; set; }
        public Nullable<int> fld_FK_AccessID { get; set; }
        public Nullable<int> fld_FK_AccessStatus { get; set; }
        public string fld_AccessLogPersonName { get; set; }
        public Nullable<int> fld_AccessLogPreviousAccessID { get; set; }
        public Nullable<bool> fld_ShowLastLog { get; set; }
        public Nullable<int> fld_AccessLogHDate { get; set; }
        public string fld_AccessLogTime { get; set; }
        public Nullable<System.DateTime> fld_AccessLogMDate { get; set; }
    
        public virtual Tbl_AccessStatus Tbl_AccessStatus { get; set; }
        public virtual Tbl_Access Tbl_Access { get; set; }
    }
}
